version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "node-lambda-dynamodb-streams"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yx0md7en37rh"
s3_prefix = "node-lambda-dynamodb-streams"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
